version: '3.8'
services:
  dev-db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
    ports:
      - 5432:5432
    networks:
      - freecodecamp
  test-db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: nest
    ports:
      - 5433:5432
    networks:
      - freecodecamp
networks:
  freecodecamp: